name: NPM / Publish

on:
  workflow_dispatch:
  push:
    paths:
      - packages/poster/**/*
    branches:
      - 'main'
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 17
      - run: yarn --immutable
      - run: yarn poster:prod
      - run: cd ./packages/poster
      - uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939 # v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
